name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Set up poetry
        run: |
          python -m pip install -U poetry
      - uses: actions/cache@v2
        id: cache-pydeps
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache-pydeps.outputs.cache-hit != 'true'
        run: |
          poetry install --no-interaction
      - name: Run flake8
        run: |
          poetry run flake8 .
      - name: Check imports
        run: |
          poetry run isort -c .
      - name: Check black
        run: |
          poetry run black --check .
      - name: mypy static type check
        run: |
          poetry run mypy .
